// Mirrors the D7 payload contract (see DECISIONS.md) generated by
// reading-challenge's pipeline. `finished` is a pending contract addition
// (agreed 2026-08-09, not yet emitted by the real pipeline) that lets the
// site tell a completed book from one still in progress without guessing
// from which metadata fields happen to be null.

export type BookFormat = 'ebook' | 'print' | 'audio';

export interface BookLink {
  id: string;
  url: string;
}

export interface Book {
  title: string;
  author: string | null;
  pages: number | null;
  /** Audiobook duration in minutes; null for ebook/print. */
  duration: number | null;
  format: BookFormat | null;
  dnf: boolean;
  /** Continuous, not stars: 0-5, one-decimal precision. Null when unrated. */
  rating: number | null;
  finished: boolean;
  /**
   * When the book was finished, at whatever precision MyBooks holds:
   * `YYYY-MM-DD`, `YYYY-MM` or `YYYY` (BRIEF §6). Null only for books still in
   * progress.
   *
   * This is what places a book with no tracked sessions. Audiobook time is not
   * tracked in Boosted, so untimed audiobooks reach the site with `date_read`
   * as their only position in time — every one of them carries full `YYYY-MM-DD`
   * precision.
   */
  date_read: string | null;
  links: Record<string, BookLink>;
}

/** Columnar: sessions.date[i]/book[i]/minutes[i]/start[i]/end[i] describe session i. */
export interface Sessions {
  /** Day offset from `Payload.epoch`. */
  date: number[];
  /** Index into `Payload.books`. */
  book: number[];
  minutes: number[];
  /**
   * Seconds since local midnight. Null when Boosted recorded no clock time for
   * the session — 3 rows in the current data. Views that need time-of-day must
   * skip these rather than assume a value; the session's `minutes` is still
   * good, so it counts everywhere else.
   */
  start: (number | null)[];
  end: (number | null)[];
}

export interface Payload {
  /** YYYY-MM-DD date that `Sessions.date` offsets are counted from (day 0). */
  epoch: string;
  books: Book[];
  sessions: Sessions;
}
